### model
model_name_or_path: /kaggle/input/llama-3.2/transformers/3b-instruct/1
reward_model: saves/Llama-3.2-3B-Instruct/lora/reward

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: identity,alpaca_zh_demo
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Llama-3.2-3B-Instruct/lora/ppo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
