### model
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
adapter_name_or_path: saves/Llama-3.2-3B-Instruct/lora/sft

### method
finetuning_type: lora

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/Llama-3.2-3B-Instruct/lora/eval

### eval
batch_size: 4
